services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db-pass
      - DB_NAME=database
      - TYPE=postgres
      - DB_SSL=false
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - postgres
    networks:
      - lean-net

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db-pass
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - lean-net

networks:
  lean-net:
    driver: bridge