### Documentation endpoints

## Endpoint to carry out value transfers between two different users. The sender must have permission to carry out the transfer.

POST http://localhost:3000/transfer
Content-Type: application/json

{
    "payer": 1,
    "payee": 2,
    "value": 100.50
}

### Endpoint to check application status

GET http://localhost:3000/status